# Generated by Django 4.0.4 on 2022-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, upload_to='music'),
        ),
    ]
