# Generated by Django 4.0.4 on 2022-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chatmessage_thread_delete_message_delete_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
