# Generated by Django 4.0.4 on 2022-06-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_threadmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
