# Generated by Django 5.1.6 on 2025-05-23 11:58

from django.db import migrations, models
import datetime

def delete_invalid_comments(apps, schema_editor):
    # Get the models
    Post = apps.get_model('core', 'Post')
    Comment = apps.get_model('core', 'Comment')
    
    # Get all valid post IDs
    valid_post_ids = set(Post.objects.values_list('id', flat=True))
    
    # Find comments with invalid post references
    invalid_comments = Comment.objects.exclude(post_id__in=valid_post_ids)
    
    # Delete invalid comments
    print(f"Deleting {invalid_comments.count()} comments with invalid post references")
    invalid_comments.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_updated_thread_updated_at_and_more'),
    ]

    operations = [
        # First, run the function to delete invalid comments
        migrations.RunPython(delete_invalid_comments),
        
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='unread_messages_count_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='unread_messages_count_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
